# Blog post meta information
title: "Using video in og tags"
description: ""
author: ""
date: ""

# Open Graph meta tags
og:
  title: "Using video in og tags"
  description: ""
  type: ""
  url: "https://spinoff.blog/using-video-in-og-tags-20240715"
  "video:secure_url": "https://spinoff.blog/media/videos/using-video-in-og-tags-20240715.mp4"
  "video:type": "video/mp4"
  site_name: "The Spinoff Blog"

# Twitter Card meta tags
twitter:
  card: ""
  site: ""
  creator: ""

# Additional meta tags
keywords:
  -
  -
  -
  -
