# Blog post meta information
title: "Value of empty residential blocks in Peppermint Grove"
description: ""
author: ""
date: ""

# Open Graph meta tags
og:
  title: "Value of empty residential blocks in Peppermint Grove"
  description: ""
  type: ""
  url: "https://spinoff.blog/value-of-empty-blocks-in-peppermint-grove-20240713"
  image: "https://spinoff.blog/media/images/value-of-empty-blocks-in-peppermint-grove-20240713.jpg"
  site_name: "The Spinoff Blog"

# Twitter Card meta tags
twitter:
  card: ""
  site: ""
  creator: ""

# Additional meta tags
keywords:
  -
  -
  -
  -
