# Blog post meta information
title: "Value of empty residential blocks in Cottesloe"
description: ""
author: ""
date: ""

# Open Graph meta tags
og:
  title: "Value of empty residential blocks in Cottesloe"
  description: ""
  type: ""
  url: ""
  image: "https://spinoff.blog/media/images/value-of-empty-blocks-in-cottesloe-20240708.jpg"
  site_name: ""

# Twitter Card meta tags
twitter:
  card: ""
  site: ""
  creator: ""

# Additional meta tags
keywords:
  - 
  - 
  - 
  -