# Blog post meta information
title: "Property sales tracker"
description: ""
author: ""
date: ""

# Open Graph meta tags
og:
  title: "Property sales tracker"
  description: ""
  type: ""
  url: "https://spinoff.blog/property-value-tracker-20240718"
  image: "https://spinoff.blog/media/images/property-value-tracker-20240718.jpg"
  site_name: "The Spinoff Blog"

# Twitter Card meta tags
twitter:
  card: ""
  site: ""
  creator: ""

# Additional meta tags
keywords:
  -
  -
  -
  -
