# Blog post meta information
title: "The Spinoff Blog - Home"
description: ""
author: ""
date: ""

# Open Graph meta tags
og:
  title: "The Spinoff Blog - Home"
  description: ""
  type: ""
  url: ""
  image: "https://spinoff.blog/media/images/home.png"
  site_name: ""

# Twitter Card meta tags
twitter:
  card: ""
  site: ""
  creator: ""

# Additional meta tags
keywords:
  - 
  - 
  - 
  -